### ISSUE TITLE
Auth 404'ed

### ISSUE THREAD

**Issue by TheMissingPort** [DIGITALCRIMINAL/UltimaScraper#1547] opened 2021-08-08 06:29 UTC
Not sure what happened. I've never had issues before. I can't get it working on both of my devices. I have silicon based Mac Mini and MacBook Air, both are not working. This is the error from my Mac Mini. The MacBook Air seems to get a bit further but still runs into errors. 

Traceback (most recent call last):
  File "/Users//Documents/Programs/OnlyFans-master/start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users//Documents/Programs/OnlyFans-master/start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "/Users//Documents/Programs/OnlyFans-master/datascraper/main_datascraper.py", line 66, in start_datascraper
    setup, subscriptions = await module.account_setup(
  File "/Users//Documents/Programs/OnlyFans-master/modules/onlyfans.py", line 87, in account_setup
    authed = await auth.login()
  File "/Users//Documents/Programs/OnlyFans-master/apis/onlyfans/classes/create_auth.py", line 132, in login
    user = await self.get_user(auth_id)
  File "/Users//Documents/Programs/OnlyFans-master/apis/onlyfans/classes/create_auth.py", line 194, in get_user
    response["session_manager"] = self.session_manager
TypeError: 'NoneType' object does not support item assignment

Any suggestions? 

Thanks

**Comment by LunarPenguin** [comment] 2021-08-09 11:48
We can not help you without a log showing what is causing the problem. please provide a log or a screenshot of what is happening up-to the exception you have posted.

**Comment by TheMissingPort** [comment] 2021-08-09 17:39
> We can not help you without a log showing what is causing the problem. please provide a log or a screenshot of what is happening up-to the exception you have posted.

Fixed

**Comment by ThrowawayDane** [comment] 2021-08-10 12:12
> > We can not help you without a log showing what is causing the problem. please provide a log or a screenshot of what is happening up-to the exception you have posted.
> 
> Fixed

If you have fixed it then please close the issue :) And maybe share the fix if someone else have the problem also. :D

**Comment by TheMissingPort** [comment] 2021-08-10 20:07
> > > We can not help you without a log showing what is causing the problem. please provide a log or a screenshot of what is happening up-to the exception you have posted.
> > 
> > 
> > Fixed
> 
> If you have fixed it then please close the issue :) And maybe share the fix if someone else have the problem also. :D

No I meant I updated the thread with the full log

**Comment by LunarPenguin** [comment] 2021-08-11 11:29
> Fixed

Thanks, have you tried it again since then? looking at the code this seems a temporary mishap caused by onlyfans.

**Comment by TheMissingPort** [comment] 2021-08-12 02:38
> > Fixed
> 
> Thanks, have you tried it again since then? looking at the code this seems a temporary mishap caused by onlyfans.

No unfortunately I'm still having the same issue

**Comment by bigbluedeer** [comment] 2021-08-14 13:06
possible duplicate of #1387

**Closed** 2023-10-21 08:50 UTC
