### ISSUE TITLE
New Error "TypeError: 'NoneType' object does not support item assignment"

### ISSUE THREAD

**Issue by Pwnager12345** [DIGITALCRIMINAL/UltimaScraper#1551] opened 2021-08-09 00:01 UTC
I was having the same issue about the "author" thing as other people are. The fix in #1419 helped me fix that but now I am getting a different error.

This is what it says: 
```
Traceback (most recent call last):
  File "/Users/username/Desktop/OnlyFans-master/start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/username/Desktop/OnlyFans-master/start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "/Users/username/Desktop/OnlyFans-master/datascraper/main_datascraper.py", line 66, in start_datascraper
    setup, subscriptions = await module.account_setup(
  File "/Users/username/Desktop/OnlyFans-master/modules/onlyfans.py", line 106, in account_setup
    subscriptions += await manage_subscriptions(
  File "/Users/username/Desktop/OnlyFans-master/modules/onlyfans.py", line 1266, in manage_subscriptions
    results = await authed.get_subscriptions(identifiers=identifiers, refresh=refresh)
  File "/Users/username/Desktop/OnlyFans-master/apis/onlyfans/classes/create_auth.py", line 312, in get_subscriptions
    results += await asyncio.gather(*tasks)
  File "/Users/username/Desktop/OnlyFans-master/apis/onlyfans/classes/create_auth.py", line 293, in multi
    tasks = await asyncio.gather(*tasks)
  File "/Users/username/Desktop/OnlyFans-master/apis/onlyfans/classes/create_auth.py", line 194, in get_user
    response["session_manager"] = self.session_manager
TypeError: 'NoneType' object does not support item assignment
```
Can anyone help me? I have practically no experience with coding so I am clueless

**Comment by snoopyh42** [comment] 2021-08-09 19:40
I get this same sort of error.  It fails out on user jess*icani*gri (asterisks to avoid her scanners)

**Comment by Pwnager12345** [comment] 2021-08-10 23:41
Okay... I just kept running, terminating, and re-running the script and it just suddenly worked on one of them? Its now showing me "Scraping subscriptions" part like normal

**Comment by bigbluedeer** [comment] 2021-08-14 12:18
The function `json_request` ("apis/api_helper.py", line 151) is probably the issue, it silences two errors (ClientConnectorError, ProxyError) which causes it to return the default value of result result = `None` ("apis/api_helper.py", line 171).

ClientConnectorError means you cannot connect to the host, OF might suspect a DOS attack (maybe you are scraping to many users).
source: https://stackoverflow.com/questions/57046073

ProxyError is probably not the cause if you are not using special proxies

**Comment by bigbluedeer** [comment] 2021-08-14 13:04
possible duplicate of #1387

**Comment by Pwnager12345** [comment] 2021-08-16 15:08
> The function `json_request` ("apis/api_helper.py", line 151) is probably the issue, it silences two errors (ClientConnectorError, ProxyError) which causes it to return the default value of result result = `None` ("apis/api_helper.py", line 171).
> 
> ClientConnectorError means you cannot connect to the host, OF might suspect a DOS attack (maybe you are scraping to many users).
> source: https://stackoverflow.com/questions/57046073
> 
> ProxyError is probably not the cause if you are not using special proxies

The error is appearing right after this part:
`Site: 0 = onlyfans | 
0
Choose Profile
Names: Username = username  | 0 = All | 1 = default
1
Auth (V1) Attempt 1/10
Welcome <my username> | username`

The fact that it's showing my username at all means the login is working, but it is supposed to say _Scrapping Paid Subscriptions_ after that. So something is breaking between logging on and when it starts scrapping.

**Closed** 2023-10-21 08:50 UTC
