### ISSUE TITLE
Error KeyError: 'author'

### ISSUE THREAD

**Issue by djmarioka** [DIGITALCRIMINAL/UltimaScraper#1653] opened 2021-08-28 16:22 UTC
Hi,

I can't download any paid subscriptions I've got, I attach a screenshot, this is the same issue:

![image](https://user-images.githubusercontent.com/81478245/131224296-f260613e-ce63-40fc-8770-b154623cc0e7.png)

Could you tell me how to fix it?. 

Regards.

**Comment by ChangeUsername** [comment] 2021-08-28 19:49
Did you try this?
https://github.com/DIGITALCRIMINAL/OnlyFans/issues/1419#issuecomment-893866110

**Comment by Gamma-Velorum** [comment] 2021-08-29 15:07
Add the user to your blacklist. Nothing else works.

**Comment by fg4jerem** [comment] 2021-09-01 03:04
> Add the user to your blacklist. Nothing else works.

That was my first, reflex, but somehow that doesn't work either. Even though I have this (see below) in my conf.json file, the user still gets scrapped and I get the error. Is it possible the blacklist gets applied later when it comes time to actually download the content?

`
"blacklists": [
          "hotsluttymilf"
        ],
`

Strangely, I don't see the "blacklists" options documented on the README, only the "blacklist_name" option which is absent from my config.json. And yes I've run the updater.py.

In any case, the workaround from @Charmoq mentionned in previous issue #1419 is working for me, and seems like a better workaround for now anyway.

Isn't this ticket a duplicate of #1419 anyway?

**Closed** 2023-10-21 08:49 UTC
