### ISSUE TITLE
Name becomes changed back to default (and TypeError)

### ISSUE THREAD

**Issue by RehistoricDinosaur** [DIGITALCRIMINAL/UltimaScraper#1621] opened 2021-08-24 01:12 UTC
I dont know much about coding
Though I have a little bit of computer common sense
So I am gonna make it short and simple:
A couple months ago I'm using the script perfectly fine.
Fast forward to now: Im getting an error.

> Scrape Attempt: 1/100
Type: Archived Posts
Processing Scraped Posts
Traceback (most recent call last):
  File "C:\Users\user\Desktop\New folder (2)\OnlyFans-7.4.1\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\user\Desktop\New folder (2)\OnlyFans-7.4.1\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "C:\Users\user\Desktop\New folder (2)\OnlyFans-7.4.1\datascraper\main_datascraper.py", line 93, in start_datascraper
    await main_helper.process_names(
  File "C:\Users\user\Desktop\New folder (2)\OnlyFans-7.4.1\helpers\main_helper.py", line 939, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "C:\Users\user\Desktop\New folder (2)\OnlyFans-7.4.1\modules\onlyfans.py", line 160, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "C:\Users\user\Desktop\New folder (2)\OnlyFans-7.4.1\modules\onlyfans.py", line 823, in prepare_scraper
    unrefined_set = await tqdm.gather(*tasks, **settings)
TypeError: gather() takes 2 positional arguments but 141 were given

One important thing I've noticed that I believe might be the problem is; when I have Notepad++ open and run script with the config.json open. It will revert the username back to 'Default' 
Also, there is no selection for specific username like in the past.

My 7.4 folder does the same thing
Sorry if I'm missing a new important step. I just figured I could download the latest version and it would work naturally.

**Comment by bigbluedeer** [comment] 2021-08-24 09:18
first error is possible duplicate of #1527

**Comment by americanseeder1865** [comment] 2021-08-25 11:46
The author does know about this, but has lost access to his main account. You version is pretty old. Let's go ahead and install from [this branch](https://github.com/DIGITALCRIMINALS/OnlyFans) for now. Reinstall and report back.

**Closed** 2023-10-21 08:50 UTC
