### ISSUE TITLE
Silicon Mac: Auth 404'd "TypeError: 'NoneType' object does not support item assignment"

### ISSUE THREAD

**Issue by TheMissingPort** [DIGITALCRIMINAL/UltimaScraper#1618] opened 2021-08-23 18:10 UTC
Getting the following error when I try to login 

Any advice? Thanks

```
Auth (V1) Attempt 1/10
Auth 404'ed
Auth (V1) Attempt 2/10
Auth 404'ed
Auth (V1) Attempt 3/10
Auth 404'ed
Auth (V1) Attempt 4/10
Auth 404'ed
Auth (V1) Attempt 5/10
Auth 404'ed
Auth (V1) Attempt 6/10
Auth 404'ed
Auth (V1) Attempt 7/10
Auth 404'ed
Auth (V1) Attempt 8/10
Auth 404'ed
Auth (V1) Attempt 9/10
Auth 404'ed
Auth (V1) Attempt 10/10
Auth 404'ed
Traceback (most recent call last):
  File "/Users//Documents/Programs/OnlyFans-master/start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users//Documents/Programs/OnlyFans-master/start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "/Users//Documents/Programs/OnlyFans-master/datascraper/main_datascraper.py", line 66, in start_datascraper
    setup, subscriptions = await module.account_setup(
  File "/Users//Documents/Programs/OnlyFans-master/modules/onlyfans.py", line 87, in account_setup
    authed = await auth.login()
  File "/Users//Documents/Programs/OnlyFans-master/apis/onlyfans/classes/create_auth.py", line 132, in login
    user = await self.get_user(auth_id)
  File "/Users//Documents/Programs/OnlyFans-master/apis/onlyfans/classes/create_auth.py", line 194, in get_user
    response["session_manager"] = self.session_manager
TypeError: 'NoneType' object does not support item assignment
```

> > Likely an issue with the current build. The Author has lost access to their main account. Let's go ahead and install from [this branch](https://github.com/DIGITALCRIMINALS/OnlyFans) for now. Reinstall and report back.
> 
> This is the first I'm seeing this. Where did he say he lost access to the account?

**Comment by LunarPenguin** [comment] 2021-08-23 18:39
Try resetting your auth details

**Comment by TheMissingPort** [comment] 2021-08-23 18:43
> Try resetting your auth details

You mean getting new cookies right? I’ve done that multiple times

**Comment by LunarPenguin** [comment] 2021-08-23 18:50
yes, not sure what you can do then

**Comment by bigbluedeer** [comment] 2021-08-24 09:05
possible duplicate of #1387

**Comment by bobsage123** [comment] 2021-08-24 23:58
I can auth in and run partly but get this on one of the subs

**Comment by americanseeder1865** [comment] 2021-08-25 11:53
Likely an issue with the current build. The Author has lost access to their main account. Let's go ahead and install from [this branch](https://github.com/DIGITALCRIMINALS/OnlyFans) for now. Reinstall and report back.

**Comment by TheMissingPort** [comment] 2021-09-06 03:51
> Likely an issue with the current build. The Author has lost access to their main account. Let's go ahead and install from [this branch](https://github.com/DIGITALCRIMINALS/OnlyFans) for now. Reinstall and report back.

It says page not found

**Comment by TheMissingPort** [comment] 2021-09-06 06:18
> Well it's probably time to containerize. Run the branch I posted earlier using Docker. Need help doing this?

I'm stuck, I get this error 

`failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount876329198/Dockerfile: no such file or directory`

I looked online, it says to fix the "DockerFile" but I don't even have a directory

**Comment by LunarPenguin** [comment] 2021-09-06 09:37
> It says page not found

It seems the alt-account of @DIGITALCRIMINAL has been deleted. i dont know if DC did this himself or if github deleted his account. I hope he is able to give some clarification on the matter.

**Comment by OFfriend** [comment] 2021-09-06 17:42
> 
> 
> > It says page not found
> 
> It seems the alt-account of @DIGITALCRIMINAL has been deleted. i dont know if DC did this himself or if github deleted his account. I hope he is able to give some clarification on the matter.

github

**Closed** 2023-10-21 08:50 UTC
